workflows:
  android-workflow:
    name: Android Alarm App Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.yourcompany.alarmapp"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/local.properties"
      - name: Build Android release without signing
        script: |
          ./gradlew assembleRelease -x test  # اطمینان از وجود gradlew و مسیر صحیح آن
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - your_email@example.com
        notify:
          success: true
          failure: false
